### ISSUE TITLE
Error while installing requirements

### ISSUE THREAD

**Issue by MarekOstrihon** [chonyy/ML-auto-baseball-pitching-overlay#9]
Hello, could you please land me a hand?

I'am getting this kind of issue:

`ImportError: cannot import name 'soft_unicode' from 'markupsafe'`  (full traceback below)

Googling this error I found that there's a mismatch in package dependencies, mainly the markupsafe library.
I played around with various versions of the packages but didn't get it in an functional state.

I tried to install it on Python 3.7, 3.8 and 3.10

Can you please update the requirements file or give a hint how to install it?

Thanks, Marek

`  ERROR: Command errored out with exit status 1:
   command: /Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/bin/python3 /Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/tmp8cv3k60q
       cwd: /private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-install-g_jmq3w8/astropy
  Complete output (28 lines):
  Traceback (most recent call last):
    File "/Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 70, in <module>
      ext_modules=get_extensions())
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/extension_helpers/_setup_helpers.py", line 67, in get_extensions
      ext_modules.extend(setuppkg.get_extensions())
    File "./astropy/modeling/setup_package.py", line 59, in get_extensions
      from jinja2 import Environment, FileSystemLoader
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/jinja2/__init__.py", line 33, in <module>
      from jinja2.environment import Environment, Template
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/jinja2/environment.py", line 15, in <module>
      from jinja2 import nodes
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/jinja2/nodes.py", line 19, in <module>
      from jinja2.utils import Markup
    File "/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/jinja2/utils.py", line 642, in <module>
      from markupsafe import Markup, escape, soft_unicode
  ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/private/var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/pip-build-env-kxuy583w/overlay/lib/python3.8/site-packages/markupsafe/__init__.py)
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/bin/python3 /Users/jardik/Documents/overlay/ML-auto-baseball-pitching-overlay/env-MLauto/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/vx/5x_d29f50t7387_bmsjsc8700000gn/T/tmp8cv3k60q Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env-MLauto) MacBook-Pro-2:ML-auto-baseball-pitching-overlay jardik$ `

**Comment by Jensen-holm** [comment]
There have been a couple of updates released since this issue, do you think you could try again? I am curious if this is still an issue.
